//Filter Options
//Map of Divisions
const divisionMap = [
    { label: "Jaipur", value: "jaipur" },
    { label: "Ajmer", value: "ajmer" },
    { label: "Ahmedabad", value: "ahmedabad" },
];

//Map of Sites
const siteMap = [
    { label: "New Rewari", value: "REJN", division: "jaipur" },
    { label: "New Ateli", value: "AELN", division: "jaipur" },
    { label: "New Dabla", value: "DBLN", division: "jaipur" },
    { label: "New Bhagega", value: "BAGN", division: "jaipur" },
    { label: "New Shri Madhopur", value: "SMPN", division: "jaipur" },
    { label: "New Malikpur", value: "PMPN", division: "jaipur" },
    { label: "New Phulera", value: "FLN", division: "jaipur" },
    { label: "New Sakhun", value: "SKNN", division: "jaipur" },
    { label: "New Kishangarh", value: "KSGN", division: "jaipur" },
    { label: "New Saradhana", value: "SDHN", division: "ajmer" },
    { label: "New Bangurgram", value: "BGMN", division: "ajmer" },
    { label: "New Haripur", value: "HPRN", division: "ajmer" },
    { label: "New Chandawal", value: "CNLN", division: "ajmer" },
    { label: "New Marwar", value: "MJND", division: "ajmer" },
    { label: "New Jawali", value: "JALN", division: "ajmer" },
    { label: "New Biroliya", value: "BRLN", division: "ajmer" },
    { label: "New Keshavganj", value: "KVJN", division: "ajmer" },
    { label: "New Banas", value: "BNSN", division: "ajmer" },
    { label: "New Swarupganj", value: "SRPN", division: "ajmer" },
    { label: "New Shri Amirgarh", value: "SMIN", division: "ajmer" },
    { label: "New Palanpur", value: "PNUN", division: "ahmedabad" },
    { label: "New Chadotar", value: "CDQN", division: "ahmedabad" },
    { label: "New Umardasi", value: "UMND", division: "ahmedabad" },
    { label: "New Mahesana", value: "MSHN", division: "ahmedabad" },
    { label: "New Ghumasan", value: "GUSN", division: "ahmedabad" },
    { label: "New Sanand North", value: "SAUN", division: "ahmedabad" },
    { label: "New Sanand South", value: "SAUS", division: "ahmedabad" },
    { label: "New Timba", value: "TBAN", division: "ahmedabad" },
    { label: "New Changa", value: "CGYN", division: "ahmedabad" },
    { label: "New Vasad", value: "VDAN", division: "ahmedabad" },
    { label: "New Makarpura", value: "MPRN", division: "ahmedabad" },
];

//Map of Blocks
const blockMap = [
    { label: "REJN-AELN", alhlist: ["A001", "A002", "A003", "A004"], value: "REJN-AELN" },
    { label: "AELN-DBLN", alhlist: ["A005", "A006", "A007", "A008", "A009", "A010"], value: "AELN-DBLN" },
    { label: "DBLN-BAGN", alhlist: ["A011", "A012", "A013", "A014", "A015"], value: "DBLN-BAGN" },
    { label: "BAGN-SMPN", alhlist: ["A016", "A017", "A018", "A019", "A020", "A021"], value: "BAGN-SMPN" },
    { label: "SMPN-PMPN", alhlist: ["A022", "A023", "A024", "A025"], value: "SMPN-PMPN" },
    { label: "PMPN-FLN", alhlist: ["A026", "A027", "A028", "A029", "A030", "A031", "A032"], value: "PMPN-FLN" },
    { label: "FLN-SKNN", alhlist: ["A033", "A034", "A035"], value: "FLN-SKNN" },
    { label: "SKNN-KSGN", alhlist: ["A036", "A037", "A038", "A039", "A040"], value: "SKNN-KSGN" },
    { label: "KSGN-SDHN", alhlist: ["A041", "A042", "A043", "A044"], value: "KSGN-SDHN" },
    { label: "SDHN-BGMN", alhlist: ["A045", "A046", "A047", "A048", "A049"], value: "SDHN-BGMN" },
    { label: "BGMN-HPRN", alhlist: ["A050", "A051", "A052", "A053", "A054", "A055"], value: "BGMN-HPRN" },
    { label: "HPRN-CNLN", alhlist: ["A056", "A057", "A058"], value: "HPRN-CNLN" },
    { label: "CNLN-MJND", alhlist: ["A059", "A060", "A061", "A062", "A063"], value: "CNLN-MJND" },
    { label: "MJND-JALN", alhlist: ["A064", "A065", "A066", "A067", "A068"], value: "MJND-JALN" },
    { label: "JALN-BRLN", alhlist: ["A069", "A070", "A071", "A072", "A073"], value: "JALN-BRLN" },
    { label: "BRLN-KVJN", alhlist: ["A074", "A075", "A076", "A077", "A078", "A079"], value: "BRLN-KVJN" },
    { label: "KVJN-BNSN", alhlist: ["A080", "A081", "A082"], value: "KVJN-BNSN" },
    { label: "BNSN-SRPN", alhlist: ["A083"], value: "BNSN-SRPN" },
    { label: "SRPN-SMIN", alhlist: ["A084", "A085", "A086", "A087", "A088", "A089"], value: "SRPN-SMIN" },
    { label: "SIMN-PNUN", alhlist: ["A090", "A091", "A092", "A093"], value: "SIMN-PNUN" },
    { label: "CDQN-PNUN", alhlist: ["A134", "A135"], value: "CDQN-PNUN" },
    { label: "PNUN-UMND", alhlist: ["A094", "A095", "A096"], value: "PNUN-UMND" },
    { label: "UMND-MSHN", alhlist: ["A097", "A098", "A099", "A100", "A101", "A102", "A103"], value: "UMND-MSHN" },
    { label: "MSHN-GUSN", alhlist: ["A104", "A105", "A106", "A107", "A108", "A109"], value: "MSHN-GUSN" },
    { label: "GUSN-SAUN", alhlist: ["A110", "A111", "A112", "A113", "A114"], value: "GUSN-SAUN" },
    { label: "SAUN-SAUS", alhlist: ["A115"], value: "SAUN-SAUS" },
    { label: "SAUS-TBAN", alhlist: ["A116", "A117", "A118"], value: "SAUS-TBAN" },
    { label: "TBAN-CGYN", alhlist: ["A119", "A120", "A121", "A122", "A123", "A124"], value: "TBAN-CGYN" },
    { label: "CGYN-VDAN", alhlist: ["A125", "A126", "A127", "A128"], value: "CGYN-VDAN" },
    { label: "VDAN-MPRN", alhlist: ["A129", "A130", "A131", "A132", "A133"], value: "VDAN-MPRN" }
];

const assetClassMap = [
    { label: "01-Main Signal", value: "01-Main Signal" },
    { label: "02-A Marker", value: "02-A Marker" },
    { label: "03-Route Indicator", value: "03-Route Indicator" },
    { label: "04-Calling-on", value: "04-Calling-on" },
    { label: "05-Dependent shunt", value: "05-Dependent shunt" },
    { label: "06-Independent shunt", value: "06-Independent shunt" },
    { label: "07-AG marker", value: "07-AG marker" },
    { label: "08-VTO", value: "08-VTO" },
    { label: "09-BSLB", value: "09-BSLB" },
    { label: "10-Point machine", value: "10-Point Machine" },
    { label: "11-Ground connection", value: "11-Ground connection" },
    { label: "12-UPS", value: "12-UPS" },
    { label: "13-AUX", value: "13-AUX" },
    { label: "14-SCVS", value: "14-SCVS" },
    { label: "15-ACO", value: "15-ACO" },
    { label: "16-ACDB", value: "16-ACDB" },
    { label: "17-Transformer", value: "17-Transformer" },
    { label: "18-Converter", value: "18-Converter" },
    { label: "19-Battery Bank", value: "19-Battery Bank" },
    { label: "20-Battery Cell", value: "20-Battery Cell" },
    { label: "21-Spare cell charger", value: "21-Spare cell charger" },
    { label: "22-Spare cell", value: "22-Spare cell" },
    { label: "23-LV Box", value: "23-LV Box" },
    { label: "24-Wheel Sensor", value: "24-Wheel Sensor" },
    { label: "25-MSDAC Rack", value: "25-MSDAC Rack" },
    { label: "26-Ethernet switch-MSDAC", value: "26-Ethernet switch-MSDAC" },
    { label: "27-Board Rack", value: "27-Board Rack" },
    { label: "28-Electronic Card-MSDAC", value: "28-Electronic Card-MSDAC" },
    { label: "29-FDS", value: "29-FDS" },
    { label: "30-Reset Box", value: "30-Reset Box" },
    { label: "31-TLJB", value: "31-TLJB" },
    { label: "32-Relay Rack", value: "32-Relay Rack" },
    { label: "33-CTR", value: "33-CTR" },
    { label: "34-VLC Rack", value: "34-VLC Rack" },
    { label: "35-IOM Rack", value: "35-IOM Rack" },
    { label: "36-EI-Terminal", value: "36-EI-Terminal" },
    { label: "37-EI-MT", value: "37-EI-MT" },
    { label: "38-Electronic Card-VLC", value: "38-Electronic Card-VLC" },
    { label: "39-Electronic Card-IOM", value: "39-Electronic Card-IOM" },
    { label: "40-PDU-EI", value: "40-PDU-EI" },
    { label: "41-VLC Sub-Rack", value: "41-VLC Sub-Rack" },
    { label: "42-IFC Sub-Rack", value: "42-IFC Sub-Rack" },
    { label: "43-IOM Sub-Rack", value: "43-IOM Sub-Rack" },
    { label: "44-Ethernet switch-VLC", value: "44-Ethernet switch-VLC" },
    { label: "45-Ethernet switch-IOM", value: "45-Ethernet switch-IOM" },
    { label: "46-Media converter", value: "46-Media converter" },
    { label: "47-Appatarus Case (LB)", value: "47-Appatarus Case (LB)" },
    { label: "48-TMS Rack", value: "48-TMS Rack" },
    { label: "49-FIU-IPC", value: "49-FIU-IPC" },
    { label: "50-Bus coupler", value: "50-Bus coupler" },
    { label: "51-PDU-TMS", value: "51-PDU-TMS" },
    { label: "52-ASM terminal", value: "52-ASM terminal" },
    { label: "53-IMSD terminal", value: "53-IMSD terminal" },
    { label: "54-Edge Device", value: "54-Edge Device" },
    { label: "55-RTU", value: "55-RTU" },
    { label: "56-Ethernet switch-IRMS", value: "56-Ethernet switch-IRMS" },
    { label: "57-LEU Rack", value: "57-LEU Rack" },
    { label: "58-LEU-Subrack", value: "58-LEU-Subrack" },
    { label: "59-Electronic Card-LEU", value: "59-Electronic Card-LEU" },
    { label: "60-Balise", value: "60-Balise" },
    { label: "61-Junction Box", value: "61-Junction Box" },
    { label: "62-PDU-LEU", value: "62-PDU-LEU" },
    { label: "63-Ethernet switch-LEU", value: "63-Ethernet switch-LEU" },
    { label: "64-UFSBI", value: "64-UFSBI" },
    { label: "65-Block telephone", value: "65-Block telephone" },
    { label: "66-Block Panel", value: "66-Block Panel" },
    { label: "67-Relay", value: "67-Relay" },
    { label: "68-KLCR", value: "68-KLCR" },
    { label: "69-Printer", value: "69-Printer" },
    { label: "70-Telephone", value: "70-Telephone" },
    { label: "71-Outdoor Cable", value: "71-Outdoor Cable" }
];

export { divisionMap, siteMap, blockMap, assetClassMap };